# Shutdowns the plugin when server is running on non-supported version for protocol
missing_protocol_shutdown = true

disabled_commands = [
    "example"
]
core_database_filename = "/data/core_database.db"
